### ISSUE TITLE
Invoke Death Note contribution contract to store a new contribution

### ISSUE THREAD

**Issue by abdelhamidbakhta** [onlydustxyz/deathnote-contributions-feeder#3]
## Description

Once we detected new contribution from a contributor, we need to invoke Death Note contribution contract to store the new contribution.

## Acceptance Criteria

- Death Note contribution contract is invoked
- Error handling of smart contract errors is correctly done

**Comment by AnthonyBuisset** [comment]
Partially done, the error management has been moved into #23
